name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@latest
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@latest
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@latest
        with:
          gradle-version: "8.12"

      - name: Build with Gradle
        run: gradle build

      - name: Archive Artifacts
        uses: actions/upload-artifact@latest
        with:
          name: Artifacts
          path: ./build/libs
